runtime: php82

env_variables:
  APP_ENV: 'production'
  APP_KEY: 'base64:1CfE+sQAZc/Q9mLBA45e3cg26SQHDmC2i2y30Qd75gA=' # ¡Mantén tu clave segura!
  APP_DEBUG: 'false'
  APP_URL: 'https://cenrad-417101.rj.r.appspot.com/'
  APP_STORAGE: '/tmp'
  VIEW_COMPILED_PATH: '/tmp'
  CACHE_DRIVER: 'file'
  LOG_CHANNEL: 'stack'
  SESSION_DRIVER: 'file'

automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    script: auto
